### ISSUE TITLE
where is cordova-browser Documentation? 

### ISSUE THREAD

**Issue by longting** [apache/cordova-browser#81]
where is cordova-browser Documentation?

**Comment by timbru31** [comment]
See https://github.com/apache/cordova-docs/issues/907 - also the correct repo is apache/cordova-docs

**Comment by longting** [comment]
Where are the configurations? this is my project config.xml。
`<platform name="browser">
        <preference name="SplashScreen" value="/images/a.jpg" />
        <preference name="AutoHideSplashScreen" value="true" />
        <preference name="SplashScreenDelay" value="3000" />
        <preference name="SplashScreenBackgroundColor" value="green" />
        <preference name="ShowSplashScreen" value="false" />
        <preference name="SplashScreenWidth" value="600" />
        <preference name="SplashScreenHeight" value="300" />
    </platform>
`

**Comment by longting** [comment]
Equivalent to no answer.   “cordova-browser” this is keyword.  where is "cordova-browser" Documentation .  "cordova" Documentation? "cordova-android" Documentation?  "cordova-ios" Documentation? where is "cordova-browser" Documentation .

**Comment by timbru31** [comment]
I've provided an answer 😉 
1. Documentation issue(s) should be raised at https://github.com/apache/cordova-docs/ since this is our centralized repository for documentation that lives at https://cordova.apache.org/docs/en/latest/
2. The linked issue states that browser documentation is currently missing. That's why there is no documentation yet, but we are aware of this issue.

**Comment by longting** [comment]
The project's README.md document can do this
